# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Qilletni Language Docs"
site_description: "Documentation, code examples, and library help for Qilletni"
site_url: "https://qilletni.dev/"
repo_url: "https://github.com/Qilletni/Qilletni"

theme:
  name: 'material'
  custom_dir: overrides
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 # Icon for light mode (sun)
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # "slate" is the dark theme scheme
      toggle:
        icon: material/brightness-4 # Icon for dark mode (moon)
        name: Switch to light mode
  features:
    - navigation.tracking
#    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.sections
#    - navigation.expand
    - navigation.prune
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.tooltips

extra_javascript:
  - js/playlist_visual.js

extra_css:
  - css/playlist_visual.css
  - css/extra.css

nav:
  - Home:
    - Welcome: index.md
    - Quickstart:
        - Getting Started: quickstart/getting_started.md
        - Spotify Integration: quickstart/spotify_integration.md
        - Tidal Integration: quickstart/tidal_integration.md
        - Last.fm Integration: quickstart/lastfm_integration.md
    - Project Structure: project_structure.md
    - Language:
        - Introduction: language/introduction.md
        - Syntax:
            - Operators: language/syntax/operators.md
            - Extension Functions: language/syntax/extension_functions.md
        - Types:
            - Built-in types: language/types/built_in_types.md
            - Entities: language/types/entities.md
            - Type system (WIP): language/types/type_system.md
        - Service Providers: language/service_providers.md
        - Documenting Code: language/documenting_code.md
        - Debugging: language/debugging.md
    - Native Binding:
      - Introduction: native_binding/introduction.md
      - Native Functions: native_binding/native_functions.md
      - Native Bind Factories: native_binding/native_bind_factories.md
      - Background Tasks: native_binding/background_tasks.md
      - Usage Examples: native_binding/usage_examples.md
    - Packages:
      - Package Management: packages/package_management.md
      - Package Development: packages/package_development.md
      - Documenting: packages/documenting.md
    - Misc:
      - Package Configs: misc/package_configs.md
      - Debugging: misc/debug.md
      - IDE Integration (WIP): misc/ide_integration.md
      - Hosting Docs (WIP): misc/hosting_docs.md
  - Official Packages:
      - Official Packages: official_packages/official_packages.md
      - Service Providers:
        - Spotify: official_packages/service_providers/spotify.md
        - Tidal: official_packages/service_providers/tidal.md
        - Last.fm: official_packages/service_providers/lastfm.md
#      - Standard Library: packages/std.md
      - JSON: official_packages/json.md
#      - Metadata: packages/metadata.md
#      - HTTP: packages/http.md
#      - Postgres: packages/postgres.md
  - Examples:
    - General: examples.md

markdown_extensions:
  - attr_list
  - toc
  - md_in_html
  - pymdownx.blocks.caption
#      permalink: true
  - tables
  - admonition
  - codehilite:
      use_pygments: true
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
